src/dump.h File Reference
#include list_config.h
#include utils/macros.h
#include log/log.h
#include log/graph_log.h
#include utils/html.h
#include utils/ptr_valid.h
Functions
void list_dump (const List *list, const VarCodeData call_data)
(Use LIST_DUMP macros) Dumps list data to log
bool list_dump_dot (const List *list, char *img_filename)
Dumps list array to dot file.
Function Documentation
list_dump()
void list_dump (const List * list, const VarCodeData call_data)
(Use LIST_DUMP macros) Dumps list data to log
Parameters
list
call_data
Definition at line 7 of file dump.cpp.
                                                              {
    assert(list);
    LOG_(HTML_BEGIN);
    LOG_(" list_dump() called from %s:%d %s\n"
         " %s[%p] initialised in %s:%d %s \n",
         call_data.file, call_data.line, call_data.func,
         list->var_data.name, list,
         list->var_data.file, list->var_data.line, list->var_data.func);
    LOG_(" {\n");
    LOG_(" real capacity = %zd\n", list->capacity);
    LOG_(" size = %zd\n", list->size);
    LOG_(" head = %zd\n", list_head(list));
    LOG_(" tail = %zd\n", list_tail(list));
    LOG_(" free_head = %zd\n", list->free_head);
    LOG_(" is_linear = %s\n", list->is_linear ? "true" : "false");
    LOG_(" {\n");
    if (!is_ptr_valid(list->arr)) {
        if (list_is_initialised(list))
            LOG_(HTML_RED(" can't read (invalid pointer)\n"));
        LOG_(" }\n"
             " }\n" HTML_END);
        return;
    }
    LOG_(" "" i | prev | next | elem\n");
    for (ssize_t i = 0; i < list->capacity; i++) {
        LOG_(" ""%3zd | %4zd | %4zd | " ELEM_T_PRINTF "\n",
             i, list->arr[i].prev, list->arr[i].next, list->arr[i].elem);
    }
    LOG_(" }\n");
    LOG_(" Ordered elements:");
    ssize_t phys_i = list_head(list);
    ssize_t log_i = 0;
    LIST_FOREACH(*list, phys_i, log_i) {
        LOG_(" " ELEM_T_PRINTF, list->arr[phys_i].elem);
    }
    LOG_("\n Physical indexes:");
    phys_i = list_head(list);
    log_i = 0;
    LIST_FOREACH(*list, phys_i, log_i) {
        LOG_(" %zu", phys_i);
    }
    LOG_("\n"
         " }\n" HTML_END);
    char img_filename[log_file.MAX_FILENAME_LEN] = {};
    list_dump_dot(list, img_filename);
    LOG_("<img src=\"../../%s\">\n", img_filename);
}
References List::arr, List::capacity, ListNode::elem, ELEM_T_PRINTF, VarCodeData::file, List::free_head, VarCodeData::func, HTML_BEGIN, HTML_END, HTML_RED, List::is_linear, is_ptr_valid(), VarCodeData::line, list_dump_dot(), LIST_FOREACH, list_head(), list_is_initialised(), list_tail(), LOG_, log_file, LogFileData::MAX_FILENAME_LEN, VarCodeData::name, ListNode::next, ListNode::prev, List::size, and List::var_data.
list_dump_dot()
bool list_dump_dot (const List * list, char * img_filename)
Dumps list array to dot file.
Parameters
list
img_filename returns image filename
Returns
true
false
Definition at line 73 of file dump.cpp.
                                                         {
    #define BACKGROUND_COLOR "\"#1f1f1f\""
    #define FONT_COLOR "\"#000000\""
    #define NODE_PREFIX "elem_"
    #define NODE_PARAMS "shape=\"record\", style=\"filled\", fillcolor=\"#6e7681\""
    #define ZERO_NODE_PARAMS "shape=\"record\", style=\"filled\", fillcolor=\"#6e7681\", color=yellow"
    assert(list);
    char dot_filename[log_file.MAX_FILENAME_LEN] = {};
    static size_t dot_number = 0;
    strcat (dot_filename, log_file.timestamp_dir);
    sprintf(dot_filename + strlen(dot_filename), "%zd", dot_number);
    strcat (dot_filename, ".dot");
    FILE* file = fopen(dot_filename, "wb");
    if (file == nullptr)
        return false;
    FPRINTF_("digraph List{\n"
             " rankdir=LR;\n"
             " graph [bgcolor=" BACKGROUND_COLOR "];\n"
             " node[color=white, fontcolor=" FONT_COLOR ", fontsize=14];\n");
    FPRINTF_(NODE_PREFIX "0 [" ZERO_NODE_PARAMS ", label=\" head = %zd | "
                                                           "tail = %zd | "
                                                           "free_tail = %zd\"];\n",
             list_head(list), list_tail(list), list->free_head);
    for (ssize_t phys_i = 1; phys_i < list->capacity; phys_i++) {
        FPRINTF_(NODE_PREFIX "%zd [" NODE_PARAMS ", label=\" <i>phys idx = %zd | ", phys_i, phys_i);
        if (list->arr[phys_i].elem == ListNode::POISON) {
            FPRINTF_("<e>elem = PZN | ");
        } else {
            FPRINTF_("<e>elem = " ELEM_T_PRINTF " | ", list->arr[phys_i].elem);
        }
        FPRINTF_("{<p>prev = %zd | <n>next = %zd}\"", list->arr[phys_i].prev, list->arr[phys_i].next);
        if (list->arr[phys_i].prev == -1)
            FPRINTF_(", color=yellow");
        FPRINTF_("];\n");
    }
    for (ssize_t phys_i = 0; phys_i < list->capacity; phys_i++) {
        if (phys_i != 0) FPRINTF_("->");
        FPRINTF_(NODE_PREFIX "%zd", phys_i);
    }
    FPRINTF_(" [weight=10000, color=transparent, arrowtail=none];\n");
    ssize_t phys_i = list_head(list);
    ssize_t log_i = 0;
    LIST_FOREACH(*list, phys_i, log_i) {
        if (list->arr[phys_i].next != 0)
            FPRINTF_(NODE_PREFIX "%zd:<n>->" NODE_PREFIX "%zd [color=green];\n", phys_i, list->arr[phys_i].next);
        /*if (list->arr[phys_i].prev != 0)
            FPRINTF_(NODE_PREFIX "%zd:<p>->" NODE_PREFIX "%zd [color=blue];\n", phys_i, list->arr[phys_i].prev);*/
    }
    phys_i = list->free_head;
    log_i = 0;
    // macros is not used because of different size clause
    for (; phys_i > 0 && log_i <= list->capacity - list->size;
           phys_i = list->arr[phys_i].next, log_i++) {
        if (list->arr[phys_i].next != 0)
            FPRINTF_(NODE_PREFIX "%zd:<n>->" NODE_PREFIX "%zd [color=yellow];\n",
                                  phys_i, list->arr[phys_i].next);
    }
    FPRINTF_("head [shape=rect, label=\"HEAD\", color=yellow, fillcolor=\"#7293ba\",style=filled];\n");
    FPRINTF_("tail [shape=rect, label=\"TAIL\", color=yellow, fillcolor=\"#7293ba\",style=filled];\n");
    FPRINTF_("free_head [shape=rect, label=\"FREE_HEAD\","
                        "color=yellow, fillcolor=\"#7293ba\", style=filled];\n");
    FPRINTF_("head->tail->free_head[weight=100, color=transparent];");
    //FPRINTF_("head->" NODE_PREFIX "%zd [color=yellow]\n", list_head(list));
    FPRINTF_("{rank=same; head; " NODE_PREFIX "%zd}\n", list_head(list));
    //FPRINTF_("tail->" NODE_PREFIX "%zd [color=yellow]\n", list_tail(list));
    FPRINTF_("{rank=same; tail; " NODE_PREFIX "%zd}\n", list_tail(list));
    //FPRINTF_("free_head->" NODE_PREFIX "%zd [color=yellow]\n", list->free_head);
    FPRINTF_("{rank=same; free_head; " NODE_PREFIX "%zd}\n", list->free_head);
    FPRINTF_("}\n");
    if (fclose(file) != 0) {
        perror("Error closing file");
        return false;
    }
    strcat (img_filename, log_file.timestamp_dir);
    sprintf(img_filename + strlen(img_filename), "%zd", dot_number++);
    strcat (img_filename, ".svg");
    if (!create_img(dot_filename, img_filename)) {
        fprintf(stderr, "Error creating dot graph\n");
        return false;
    }
    return true;
}
References List::arr, BACKGROUND_COLOR, List::capacity, create_img(), ListNode::elem, ELEM_T_PRINTF, FONT_COLOR, FPRINTF_, List::free_head, LIST_FOREACH, list_head(), list_tail(), log_file, LogFileData::MAX_FILENAME_LEN, ListNode::next, NODE_PARAMS, NODE_PREFIX, ListNode::POISON, ListNode::prev, List::size, LogFileData::timestamp_dir, and ZERO_NODE_PARAMS.
Referenced by list_dump().