src/list.cpp File Reference
#include list.h
Macros
#define CHECK_AND_RETURN(clause_, error_, ...)
#define CHECK_ERR_(clause, err) if (clause) res |= err
Functions
int list_ctor (List *list, size_t init_capacity)
(Use macros LIST_CTOR or LIST_CTOR_CAP) List constructor
int list_dtor (List *list)
List destructor.
int list_resize (List *list, size_t new_capacity)
Resizes list (realloc)
int list_linearise (List *list, ssize_t new_capacity)
Linearises array in list. Creates new array and replaces old one.
int list_find_by_logical_index (const List *list, ssize_t logical_i, ssize_t *physical_i)
Returns physical index of element with given logical index.
int list_find_by_value (const List *list, const Elem_t elem, ssize_t *physical_i)
Returns physical index of element with given value (the first one)
int list_logical_index_by_physical (const List *list, const ssize_t physical_i, ssize_t *logical_i)
Returns logical index of element with specified logical index.
int list_verify (const List *list)
(Use macros LIST_VERIFY) Verifies list data and fields
int list_insert_after (List *list, const size_t position, const Elem_t elem, size_t *inserted_index)
Inserts element after physical index.
int list_delete (List *list, const size_t position, const bool no_resize)
Deletes element by physical index.
Variables
LogFileData log_file
Macro Definition Documentation
CHECK_AND_RETURN
#define CHECK_AND_RETURN(clause_, error_, ...)
Value:
                                                    if (clause_) { \
                                                    res |= error_; \
                                                    LIST_OK(list, res); \
                                                    __VA_ARGS__; \
                                                    return res; \
                                                }
Definition at line 5 of file list.cpp.
CHECK_ERR_
#define CHECK_ERR_(clause, err) if (clause) res |= err
Definition at line 205 of file list.cpp.
Function Documentation
list_ctor()
int list_ctor (List * list, size_t init_capacity = List::DEFAULT_CAPACITY)
(Use macros LIST_CTOR or LIST_CTOR_CAP) List constructor
Parameters
list
init_capacity
Returns
int
Definition at line 12 of file list.cpp.
                                                {
    assert(list);
    int res = list->OK;
    CHECK_AND_RETURN(list_is_initialised(list), list->ALREADY_INITIALISED);
    init_capacity++; //< fake element
    list->arr = (ListNode*)calloc(init_capacity, sizeof(ListNode));
    CHECK_AND_RETURN(list->arr == nullptr, list->ALLOC_ERR);
    list->capacity = init_capacity;
    list->arr[0] = {.prev = 0, .elem = ListNode::POISON, .next = 0};
    for (ssize_t i = 1; i < list->capacity; i++) {
        list->arr[i].elem = ListNode::POISON;
        list->arr[i].prev = ListNode::EMPTY_INDEX;
        list->arr[i].next = i + 1;
    }
    list->arr[list->capacity - 1].next = 0;
    list->free_head = 1;
    list->size = 0;
    list->is_linear = true;
    return res | LIST_ASSERT(list);
}
References List::ALLOC_ERR, List::ALREADY_INITIALISED, List::arr, List::capacity, CHECK_AND_RETURN, ListNode::elem, ListNode::EMPTY_INDEX, List::free_head, List::is_linear, LIST_ASSERT, list_is_initialised(), ListNode::next, List::OK, ListNode::POISON, ListNode::prev, and List::size.
list_delete()
int list_delete (List * list, const size_t position, const bool no_resize = false)
Deletes element by physical index.
Parameters
list
position physical index
no_resize will not resize down capacity if true
Returns
int
Definition at line 287 of file list.cpp.
                                                                         {
    int res = LIST_ASSERT(list);
    CHECK_AND_RETURN(list->arr[position].prev == -1, list->INVALID_POSITION);
    if (!no_resize) {
        res |= list_resize_down(list);
        if (res != list->OK)
            return res;
    }
    list->arr[list->arr[position].prev].next = list->arr[position].next;
    list->arr[list->arr[position].next].prev = list->arr[position].prev;
    list->arr[position].prev = list->UNITIALISED_VAL;
    list->arr[position].next = list->free_head;
    list->free_head = position;
    list->arr[position].elem = ListNode::POISON;
    list->size--;
    if ((ssize_t)position != list_head(list) && (ssize_t)position != list_tail(list))
        list->is_linear = false;
    return res | LIST_ASSERT(list);
}
References List::arr, CHECK_AND_RETURN, ListNode::elem, List::free_head, List::INVALID_POSITION, List::is_linear, LIST_ASSERT, list_head(), list_resize_down(), list_tail(), ListNode::next, List::OK, ListNode::POISON, ListNode::prev, List::size, and List::UNITIALISED_VAL.
list_dtor()
int list_dtor (List * list)
List destructor.
Parameters
list
Returns
int
Definition at line 44 of file list.cpp.
                          {
    int res = LIST_VERIFY(list);
    LIST_OK(list, res);
    fill(list->arr, list->capacity, &POISON_LIST_NODE, sizeof(POISON_LIST_NODE));
    FREE(list->arr);
    list->capacity = list->UNITIALISED_VAL;
    list->free_head = list->UNITIALISED_VAL;
    list->size = list->UNITIALISED_VAL;
    list->is_linear = false;
    return res;
}
References List::arr, List::capacity, fill(), FREE, List::free_head, List::is_linear, LIST_OK, LIST_VERIFY, POISON_LIST_NODE, List::size, and List::UNITIALISED_VAL.
Referenced by main().
list_find_by_logical_index()
int list_find_by_logical_index (const List * list, ssize_t logical_i, ssize_t * physical_i)
Returns physical index of element with given logical index.
Parameters
list
logical_i
physical_i returnable value. -1 if not found
Returns
int
Definition at line 119 of file list.cpp.
                                                                                         {
    assert(physical_i);
    int res = LIST_ASSERT(list);
    CHECK_AND_RETURN(logical_i >= list->size || logical_i < 0, list->INVALID_POSITION, {
                                                               *physical_i = -1;});
    if (list->is_linear) {
        *physical_i = logical_i + 1;
        return res;
    }
    ssize_t phys_i = list_head(list);
    ssize_t log_i = 0;
    LIST_FOREACH(*list, phys_i, log_i) {
        if (logical_i-- == 0) {
            *physical_i = phys_i;
            return res;
        }
    }
    LIST_IS_FOREACH_VALID(*list, log_i, {
        res |= list->DAMAGED_PATH;
        LIST_OK(list, res);
    });
    *physical_i = -1;
    return res;
}
References CHECK_AND_RETURN, List::DAMAGED_PATH, List::is_linear, LIST_ASSERT, LIST_FOREACH, list_head(), LIST_IS_FOREACH_VALID, LIST_OK, and List::size.
list_find_by_value()
int list_find_by_value (const List * list, const Elem_t elem, ssize_t * physical_i)
Returns physical index of element with given value (the first one)
Parameters
list
elem
physical_i returnable value. -1 if not found
Returns
int
Definition at line 149 of file list.cpp.
                                                                                 {
    assert(physical_i);
    int res = LIST_ASSERT(list);
    CHECK_AND_RETURN(elem == ListNode::POISON, list->POISON_VAL_FOUND, {
                                               *physical_i = -1;});
    ssize_t phys_i = list_head(list);
    ssize_t log_i = 0;
    LIST_FOREACH(*list, phys_i, log_i) {
        if (list->arr[phys_i].elem == elem) {
            *physical_i = phys_i;
            return res;
        }
    }
    LIST_IS_FOREACH_VALID(*list, log_i, {
        res |= list->DAMAGED_PATH;
        LIST_OK(list, res);
    });
    *physical_i = -1;
    return res;
}
References List::arr, CHECK_AND_RETURN, List::DAMAGED_PATH, ListNode::elem, LIST_ASSERT, LIST_FOREACH, list_head(), LIST_IS_FOREACH_VALID, LIST_OK, ListNode::POISON, and List::POISON_VAL_FOUND.
list_insert_after()
int list_insert_after (List * list, const size_t position, const Elem_t elem, size_t * inserted_index)
Inserts element after physical index.
Parameters
list
position physical index
elem
inserted_index returns physical index of inserted element
Returns
int
Definition at line 259 of file list.cpp.
                                                                                                    {
    int res = LIST_ASSERT(list);
    CHECK_AND_RETURN(list->arr[position].prev == -1, list->INVALID_POSITION);
    res |= list_resize_up(list);
    if (res != list->OK)
        return res;
    *inserted_index = list->free_head;
    list->free_head = list->arr[*inserted_index].next;
    list->arr[*inserted_index].prev = position;
    list->arr[*inserted_index].next = list->arr[position].next;
    list->arr[list->arr[position].next].prev = *inserted_index;
    list->arr[position].next = *inserted_index;
    list->arr[*inserted_index].elem = elem;
    list->size++;
    if ((ssize_t)*inserted_index != list_tail(list) && (ssize_t)*inserted_index != list_head(list))
        list->is_linear = false;
    return res | LIST_ASSERT(list);
}
References List::arr, CHECK_AND_RETURN, ListNode::elem, List::free_head, List::INVALID_POSITION, List::is_linear, LIST_ASSERT, list_head(), list_resize_up(), list_tail(), ListNode::next, List::OK, ListNode::prev, and List::size.
Referenced by list_insert_before(), list_pushback(), and main().
list_linearise()
int list_linearise (List * list, ssize_t new_capacity = -1)
Linearises array in list. Creates new array and replaces old one.
Parameters
list
new_capacity -1 if same as old
Returns
int
Definition at line 72 of file list.cpp.
                                                     {
    int res = LIST_ASSERT(list);
    if (new_capacity == -1) {
        new_capacity = list->capacity;
    }
    ListNode* new_arr = (ListNode*)calloc(new_capacity, sizeof(ListNode));
    CHECK_AND_RETURN(new_arr == nullptr, list->ALLOC_ERR);
    new_arr[0] = {.prev = 0, .elem = ListNode::POISON, .next = 0};
    ssize_t phys_i = list_head(list);
    ssize_t log_i = 0;
    LIST_FOREACH(*list, phys_i, log_i) {
        new_arr[log_i].next = log_i + 1;
        new_arr[log_i + 1] = {.prev = log_i, .elem = list->arr[phys_i].elem, .next = 0};
    }
    LIST_IS_FOREACH_VALID(*list, log_i, {
        res |= list->DAMAGED_PATH;
        LIST_OK(list, res);
        return res;
    });
    new_arr[0].prev = log_i;
    list->free_head = log_i + 1;
    for (phys_i = list->free_head; phys_i < (ssize_t)new_capacity; phys_i++)
        new_arr[phys_i] = {.prev = list->UNITIALISED_VAL, .elem = ListNode::POISON,
                           .next = phys_i + 1};
    new_arr[phys_i - 1].next = 0;
    FREE(list->arr);
    list->arr = new_arr;
    list->capacity = new_capacity;
    list->is_linear = true;
    return res | LIST_ASSERT(list);
}
References List::ALLOC_ERR, List::arr, List::capacity, CHECK_AND_RETURN, List::DAMAGED_PATH, ListNode::elem, FREE, List::free_head, List::is_linear, LIST_ASSERT, LIST_FOREACH, list_head(), LIST_IS_FOREACH_VALID, LIST_OK, ListNode::next, ListNode::POISON, ListNode::prev, and List::UNITIALISED_VAL.
Referenced by list_resize().
list_logical_index_by_physical()
int list_logical_index_by_physical (const List * list, const ssize_t physical_i, ssize_t * logical_i)
Returns logical index of element with specified logical index.
Parameters
list
physical_i
logical_i returnable value. -1 if not found
Returns
int
Definition at line 175 of file list.cpp.
                                                                                                   {
    assert(logical_i);
    int res = LIST_ASSERT(list);
    CHECK_AND_RETURN(physical_i >= list->capacity || physical_i <= 0, list->INVALID_POSITION, {
                                                                      *logical_i = -1;});
    if (list->is_linear) {
        *logical_i = physical_i - 1;
        return res;
    }
    ssize_t phys_i = list_head(list);
    ssize_t log_i = 0;
    LIST_FOREACH(*list, phys_i, log_i) {
        if (physical_i == phys_i) {
            *logical_i = log_i;
            return res;
        }
    }
    LIST_IS_FOREACH_VALID(*list, log_i, {
        res |= list->DAMAGED_PATH;
        LIST_OK(list, res);
    });
    *logical_i = -1;
    return res;
}
References List::capacity, CHECK_AND_RETURN, List::DAMAGED_PATH, List::is_linear, LIST_ASSERT, LIST_FOREACH, list_head(), LIST_IS_FOREACH_VALID, and LIST_OK.
list_resize()
int list_resize (List * list, size_t new_capacity)
Resizes list (realloc)
Parameters
list
new_capacity
Returns
int
Definition at line 60 of file list.cpp.
                                                 {
    int res = LIST_ASSERT(list);
    assert((ssize_t)new_capacity != list->capacity);
    res |= list_linearise(list, new_capacity);
    if (res != list->OK)
        return res;
    return res | LIST_ASSERT(list);
}
References List::capacity, LIST_ASSERT, list_linearise(), and List::OK.
Referenced by list_resize_down(), and list_resize_up().
list_verify()
int list_verify (const List * list)
(Use macros LIST_VERIFY) Verifies list data and fields
Parameters
list
Returns
int
Definition at line 207 of file list.cpp.
                                  {
    assert(list);
    int res = list->OK;
    CHECK_AND_RETURN(!list_is_initialised(list), list->UNITIALISED);
    bool is_data_valid = true;
    if (!is_ptr_valid(list->arr)) {
        res |= list->DATA_INVALID_PTR;
        is_data_valid = false;
    }
    CHECK_ERR_(list->capacity < list->size + 1, list->LOW_CAPACITY);
    CHECK_ERR_(list->capacity < 0, list->NEGATIVE_CAPACITY);
    CHECK_ERR_(list->size < 0, list->NEGATIVE_SIZE);
    CHECK_ERR_(list->free_head <= 0, list->INVALID_FREE_HEAD);
    if (!is_data_valid)
        return res;
    CHECK_ERR_(list_tail(list) < 0, list->INVALID_TAIL);
    CHECK_ERR_(list_head(list) < 0, list->INVALID_HEAD);
    ssize_t prev_phys_i = 0;
    ssize_t phys_i = list_head(list);
    ssize_t log_i = 0;
    LIST_FOREACH(*list, phys_i, log_i) {
        CHECK_ERR_(list->arr[phys_i].elem == ListNode::POISON, list->POISON_VAL_FOUND);
        CHECK_ERR_(list->arr[phys_i].prev != prev_phys_i, list->DAMAGED_PATH);
        CHECK_ERR_(list->is_linear && phys_i != log_i + 1, list->INVALID_IS_LINEAR);
        prev_phys_i = phys_i;
    }
    CHECK_ERR_(log_i != list->size, list->DAMAGED_PATH);
    CHECK_ERR_(phys_i < 0, list->DAMAGED_PATH);
    for (phys_i = 1; phys_i < list->capacity; phys_i++) {
        CHECK_ERR_(list->arr[phys_i].prev != -1 && list->arr[phys_i].elem == ListNode::POISON,
                                                                        list->POISON_VAL_FOUND);
        CHECK_ERR_(list->arr[phys_i].prev == -1 && list->arr[phys_i].elem != ListNode::POISON,
                                                                        list->NON_POISON_EMPTY);
    }
    return res;
}
References List::arr, List::capacity, CHECK_AND_RETURN, CHECK_ERR_, List::DAMAGED_PATH, List::DATA_INVALID_PTR, ListNode::elem, List::free_head, List::INVALID_FREE_HEAD, List::INVALID_HEAD, List::INVALID_IS_LINEAR, List::INVALID_TAIL, List::is_linear, is_ptr_valid(), LIST_FOREACH, list_head(), list_is_initialised(), list_tail(), List::LOW_CAPACITY, List::NEGATIVE_CAPACITY, List::NEGATIVE_SIZE, List::NON_POISON_EMPTY, List::OK, ListNode::POISON, List::POISON_VAL_FOUND, ListNode::prev, List::size, and List::UNITIALISED.
Variable Documentation
log_file
LogFileData log_file [extern]
Definition at line 4 of file main.cpp.
Referenced by main().