src/list.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <assert.h>
#include utils/macros.h
#include log/log.h
#include utils/html.h
#include utils/ptr_valid.h
Classes
struct ListNode
struct List
Specifies List data.
Macros
#define DEBUG
#define ELEM_T_PRINTF %d
#define LIST_CTOR(list) list_ctor_debug(list, VAR_CODE_DATA_PTR(list));
Constructor.
#define LIST_CTOR_CAP(list, cap) list_ctor_debug(list, VAR_CODE_DATA_PTR(list), cap);
Constructor with init capacity.
#define LIST_VERIFY(list) list_verify(list)
Verifies list data and fields.
#define LIST_ASSERT(list)
List assert macros (LIST_VERIFY, LIST_OK, and if not ok - return)
#define LIST_OK(list, res)
Checks if res is OK, if not, prints error and dump.
#define LIST_DUMP(list) list_dump(list, VAR_CODE_DATA())
Prints list dump to log.
Typedefs
typedef int Elem_t
Functions
int list_ctor (List *list, size_t init_capacity=List::DEFAULT_CAPACITY)
(Use macros LIST_CTOR or LIST_CTOR_CAP) List constructor
int list_dtor (List *list)
List destructor.
ssize_t list_head (const List *list)
Returns list head index.
ssize_t list_tail (const List *list)
Returns list tail index.
int list_insert_after (List *list, const size_t position, const Elem_t elem, size_t *inserted_index)
Inserts element after physical index.
int list_insert_before (List *list, const size_t position, const Elem_t elem, size_t *inserted_index)
Inserts element before physical index.
int list_pushback (List *list, const Elem_t elem, size_t *inserted_index)
Inserts element at the end of the list.
int list_pushfront (List *list, const Elem_t elem, size_t *inserted_index)
Inserys element at the beginning of the list.
int list_delete (List *list, const size_t position, const bool no_resize=false)
Deletes element by physical index.
void list_print_error (const int err_code)
Prints text error to log by error code.
void list_dump (const List *list, const VarCodeData call_data)
(Use LIST_DUMP macros) Dumps list data to log
int list_verify (const List *list)
(Use macros LIST_VERIFY) Verifies list data and fields
int list_resize (List *list, size_t new_capacity)
Resizes list (realloc)
int list_linearise (List *list, ListNode **dest, ssize_t *dest_free_head, size_t dest_capacity)
Creates new data array and copies list elements, but in logical sequence.
int list_find_by_logical_index (const List *list, ssize_t logical_i, ssize_t *physical_i)
Returns physical index of element with given logical index.
int list_find_by_value (const List *list, const Elem_t elem, ssize_t *physical_i)
Returns physical index of element with given value (the first one)
int list_logical_index_by_physical (const List *list, const ssize_t physical_i, ssize_t *logical_i)
Returns logical index of element with specified logical index.
bool list_is_initialised (const List *list)
Returns true if list was initialised.
int list_ctor_debug (List *list, const VarCodeData var_data, size_t init_capacity=List::DEFAULT_CAPACITY)
(Use macros LIST_CTOR or LIST_CTOR_CAP) Constructor wrapper for debug mode
int list_resize_up (List *list)
Checks if list capacity is low and resizes it.
int list_resize_down (List *list)
Checks if list capacity is too big and resizes it.
Variables
const ListNode POISON_LIST_NODE
Macro Definition Documentation
DEBUG
#define DEBUG
Definition at line 14 of file list.h.
ELEM_T_PRINTF
#define ELEM_T_PRINTF %d
Definition at line 18 of file list.h.
LIST_ASSERT
#define LIST_ASSERT(list)
Value:
                LIST_VERIFY(list); \
                LIST_OK(list, res); \
                                    \
                if (res != list->OK)\
                    return res
List assert macros (LIST_VERIFY, LIST_OK, and if not ok - return)
Parameters
list
Definition at line 301 of file list.h.
LIST_CTOR
#define LIST_CTOR(list) list_ctor_debug(list, VAR_CODE_DATA_PTR(list));
Constructor.
Parameters
list
Definition at line 280 of file list.h.
LIST_CTOR_CAP
#define LIST_CTOR_CAP(list, cap) list_ctor_debug(list, VAR_CODE_DATA_PTR(list), cap);
Constructor with init capacity.
Parameters
list
Definition at line 287 of file list.h.
LIST_DUMP
#define LIST_DUMP(list) list_dump(list, VAR_CODE_DATA())
Prints list dump to log.
Parameters
list
Definition at line 326 of file list.h.
LIST_OK
#define LIST_OK(list, res)
Value:
                                    do { \
                                    if (res != list->OK) { \
                                        list_print_error(res); \
                                        LIST_DUMP(list); \
                                    } \
                                } while (0)
Checks if res is OK, if not, prints error and dump.
Parameters
list
res
Definition at line 314 of file list.h.
LIST_VERIFY
#define LIST_VERIFY(list) list_verify(list)
Verifies list data and fields.
Parameters
list
Definition at line 294 of file list.h.
Typedef Documentation
Elem_t
typedef int Elem_t
Definition at line 16 of file list.h.
Function Documentation
list_ctor()
int list_ctor (List * list, size_t init_capacity = List::DEFAULT_CAPACITY)
(Use macros LIST_CTOR or LIST_CTOR_CAP) List constructor
Parameters
list
init_capacity
Returns
int
Definition at line 5 of file list.cpp.
                                                {
    assert(list);
    int res = list->OK;
    if (list_is_initialised(list)) {
        return res | list->ALREADY_INITIALISED;
    }
    init_capacity++; //< fake element
    list->arr = (ListNode*)calloc(init_capacity, sizeof(ListNode));
    if (list->arr == nullptr) {
        res |= list->ALLOC_ERR;
        LIST_OK(list, res);
        return res;
    }
    list->capacity = init_capacity;
    list->arr[0] = {.prev = 0, .elem = ListNode::POISON, .next = 0};
    for (ssize_t i = 1; i < list->capacity; i++) {
        list->arr[i].elem = ListNode::POISON;
        list->arr[i].prev = ListNode::EMPTY_INDEX;
        list->arr[i].next = i + 1;
    }
    list->arr[list->capacity - 1].next = 0;
    list->free_head = 1;
    list->size = 0;
    list->is_linear = true;
    return res | LIST_ASSERT(list);
}
References List::ALLOC_ERR, List::ALREADY_INITIALISED, List::arr, List::capacity, ListNode::elem, ListNode::EMPTY_INDEX, List::free_head, List::is_linear, LIST_ASSERT, list_is_initialised(), LIST_OK, ListNode::next, List::OK, ListNode::POISON, ListNode::prev, and List::size.
Referenced by list_ctor_debug().
list_ctor_debug()
int list_ctor_debug (List * list, const VarCodeData var_data, size_t init_capacity = List::DEFAULT_CAPACITY)
(Use macros LIST_CTOR or LIST_CTOR_CAP) Constructor wrapper for debug mode
Parameters
list
var_data
init_capacity
Returns
int
Definition at line 450 of file list.cpp.
                                                                                  {
    assert(list);
    list->var_data = var_data;
    return list_ctor(list, init_capacity);
}
References list_ctor(), and List::var_data.
list_delete()
int list_delete (List * list, const size_t position, const bool no_resize = false)
Deletes element by physical index.
Parameters
list
position physical index
no_resize will not resize down capacity if true
Returns
int
Definition at line 417 of file list.cpp.
                                                                         {
    int res = LIST_ASSERT(list);
    if (list->arr[position].prev == -1) {
        res |= list->INVALID_POSITION;
        return res;
    }
    if (!no_resize) {
        res |= list_resize_down(list);
        if (res != list->OK)
            return res;
    }
    list->arr[list->arr[position].prev].next = list->arr[position].next;
    list->arr[list->arr[position].next].prev = list->arr[position].prev;
    list->arr[position].prev = list->UNITIALISED_VAL;
    list->arr[position].next = list->free_head;
    list->free_head = position;
    list->arr[position].elem = ListNode::POISON;
    list->size--;
    if ((ssize_t)position != list_head(list) && (ssize_t)position != list_tail(list))
        list->is_linear = false;
    return res | LIST_ASSERT(list);
}
References List::arr, ListNode::elem, List::free_head, List::INVALID_POSITION, List::is_linear, LIST_ASSERT, list_head(), list_resize_down(), list_tail(), ListNode::next, List::OK, ListNode::POISON, ListNode::prev, List::size, and List::UNITIALISED_VAL.
list_dtor()
int list_dtor (List * list)
List destructor.
Parameters
list
Returns
int
Definition at line 43 of file list.cpp.
                          {
    int res = LIST_VERIFY(list);
    LIST_OK(list, res);
    fill(list->arr, list->capacity, &POISON_LIST_NODE, sizeof(POISON_LIST_NODE));
    FREE(list->arr);
    list->capacity = list->UNITIALISED_VAL;
    list->free_head = list->UNITIALISED_VAL;
    list->size = list->UNITIALISED_VAL;
    list->is_linear = false;
    return res;
}
References List::arr, List::capacity, fill(), FREE, List::free_head, List::is_linear, LIST_OK, LIST_VERIFY, POISON_LIST_NODE, List::size, and List::UNITIALISED_VAL.
Referenced by main().
list_dump()
void list_dump (const List * list, const VarCodeData call_data)
(Use LIST_DUMP macros) Dumps list data to log
Parameters
list
call_data
Definition at line 238 of file list.cpp.
                                                              {
    assert(list);
    LOG_(HTML_BEGIN);
    LOG_(" list_dump() called from %s:%d %s\n"
         " %s[%p] initialised in %s:%d %s \n",
         call_data.file, call_data.line, call_data.func,
         list->var_data.name, list,
         list->var_data.file, list->var_data.line, list->var_data.func);
    LOG_(" {\n");
    LOG_(" real capacity = %zd\n", list->capacity);
    LOG_(" size = %zd\n", list->size);
    LOG_(" head = %zd\n", list_head(list));
    LOG_(" tail = %zd\n", list_tail(list));
    LOG_(" free_head = %zd\n", list->free_head);
    LOG_(" is_linear = %s\n", list->is_linear ? "true" : "false");
    LOG_(" {\n");
    if (!is_ptr_valid(list->arr)) {
        if (list_is_initialised(list))
            LOG_(HTML_RED(" can't read (invalid pointer)\n"));
        LOG_(" }\n"
             " }\n" HTML_END);
        return;
    }
    LOG_(" "" i | prev | next | elem\n");
    for (ssize_t i = 0; i < list->capacity; i++) {
        LOG_(" ""%3zd | %4zd | %4zd | " ELEM_T_PRINTF "\n",
             i, list->arr[i].prev, list->arr[i].next, list->arr[i].elem);
    }
    LOG_(" }\n");
    LOG_(" Elements:");
    ssize_t i = list_head(list);
    ssize_t log_i = 0;
    while (i != 0) {
        LOG_(" " ELEM_T_PRINTF, list->arr[i].elem);
        if (++log_i > list->size) {
            LIST_OK(list, list->DAMAGED_PATH);
            return;
        }
        i = list->arr[i].next;
    }
    LOG_("\n"
         " }\n" HTML_END);
}
References List::arr, List::capacity, List::DAMAGED_PATH, ListNode::elem, ELEM_T_PRINTF, VarCodeData::file, List::free_head, VarCodeData::func, HTML_BEGIN, HTML_END, HTML_RED, List::is_linear, is_ptr_valid(), VarCodeData::line, list_head(), list_is_initialised(), LIST_OK, list_tail(), LOG_, VarCodeData::name, ListNode::next, ListNode::prev, List::size, and List::var_data.
list_find_by_logical_index()
int list_find_by_logical_index (const List * list, ssize_t logical_i, ssize_t * physical_i)
Returns physical index of element with given logical index.
Parameters
list
logical_i
physical_i returnable value. -1 if not finded
Returns
int
Definition at line 131 of file list.cpp.
                                                                                         {
    assert(physical_i);
    int res = LIST_ASSERT(list);
    if (logical_i >= list->size || logical_i < 0) {
        res |= list->INVALID_POSITION;
        LIST_OK(list, res);
        *physical_i = -1;
        return res;
    }
    ssize_t i = list_head(list);
    ssize_t log_i = 0;
    while (i > 0) {
        if (logical_i-- == 0) {
            *physical_i = i;
            return res;
        }
        if (++log_i > list->size) {
            res |= list->DAMAGED_PATH;
            LIST_OK(list, res);
            *physical_i = -1;
            return res;
        }
        i = list->arr[i].next;
    }
    *physical_i = -1;
    return res;
}
References List::arr, List::DAMAGED_PATH, List::INVALID_POSITION, LIST_ASSERT, list_head(), LIST_OK, ListNode::next, and List::size.
list_find_by_value()
int list_find_by_value (const List * list, const Elem_t elem, ssize_t * physical_i)
Returns physical index of element with given value (the first one)
Parameters
list
elem
physical_i returnable value. -1 if not finded
Returns
int
Definition at line 166 of file list.cpp.
                                                                                 {
    assert(physical_i);
    int res = LIST_ASSERT(list);
    if (elem == ListNode::POISON) {
        res |= list->POISON_VAL_FOUND;
        LIST_OK(list, res);
        *physical_i = -1;
        return res;
    }
    ssize_t i = list_head(list);
    ssize_t log_i = 0;
    while (i > 0) {
        if (list->arr[i].elem == elem) {
            *physical_i = i;
            return res;
        }
        if (++log_i > list->size) {
            res |= list->DAMAGED_PATH;
            LIST_OK(list, res);
            *physical_i = -1;
            return res;
        }
        i = list->arr[i].next;
    }
    *physical_i = -1;
    return res;
}
References List::arr, List::DAMAGED_PATH, ListNode::elem, LIST_ASSERT, list_head(), LIST_OK, ListNode::next, ListNode::POISON, List::POISON_VAL_FOUND, and List::size.
list_head()
ssize_t list_head (const List * list) [inline]
Returns list head index.
Parameters
list
Returns
ssize_t
Definition at line 104 of file list.h.
                                           {
    return list->arr[0].next;
}
References List::arr, and ListNode::next.
Referenced by list_delete(), list_dump(), list_find_by_logical_index(), list_find_by_value(), list_insert_after(), list_linearise(), list_logical_index_by_physical(), list_pushfront(), and list_verify().
list_insert_after()
int list_insert_after (List * list, const size_t position, const Elem_t elem, size_t * inserted_index)
Inserts element after physical index.
Parameters
list
position physical index
elem
inserted_index returns physical index of inserted element
Returns
int
Definition at line 386 of file list.cpp.
                                                                                                    {
    int res = LIST_ASSERT(list);
    if (list->arr[position].prev == -1) {
        res |= list->INVALID_POSITION;
        return res;
    }
    res |= list_resize_up(list);
    if (res != list->OK)
        return res;
    *inserted_index = list->free_head;
    list->free_head = list->arr[*inserted_index].next;
    list->arr[*inserted_index].prev = position;
    list->arr[*inserted_index].next = list->arr[position].next;
    list->arr[list->arr[position].next].prev = *inserted_index;
    list->arr[position].next = *inserted_index;
    list->arr[*inserted_index].elem = elem;
    list->size++;
    if ((ssize_t)*inserted_index != list_tail(list) && (ssize_t)*inserted_index != list_head(list))
        list->is_linear = false;
    return res | LIST_ASSERT(list);
}
References List::arr, ListNode::elem, List::free_head, List::INVALID_POSITION, List::is_linear, LIST_ASSERT, list_head(), list_resize_up(), list_tail(), ListNode::next, List::OK, ListNode::prev, and List::size.
Referenced by list_insert_before(), list_pushback(), and main().
list_insert_before()
int list_insert_before (List * list, const size_t position, const Elem_t elem, size_t * inserted_index) [inline]
Inserts element before physical index.
Parameters
list
position physical index
elem
inserted_index returns physical index of inserted element
Returns
int
Definition at line 138 of file list.h.
                                                                                                            {
    return list_insert_after(list, list->arr[position].prev, elem, inserted_index);
}
References List::arr, list_insert_after(), and ListNode::prev.
Referenced by list_pushfront().
list_is_initialised()
bool list_is_initialised (const List * list) [inline]
Returns true if list was initialised.
Parameters
list
Returns
true
false
Definition at line 256 of file list.h.
                                                  {
    return !(list->free_head == list->UNITIALISED_VAL &&
             list->capacity == list->UNITIALISED_VAL &&
             list->size == list->UNITIALISED_VAL &&
             list->is_linear == false && list->arr == nullptr);
}
References List::arr, List::capacity, List::free_head, List::is_linear, List::size, and List::UNITIALISED_VAL.
Referenced by list_ctor(), list_dump(), and list_verify().
list_linearise()
int list_linearise (List * list, ListNode ** dest, ssize_t * dest_free_head, size_t dest_capacity)
Creates new data array and copies list elements, but in logical sequence.
Parameters
list
dest new array pointer
dest_free_head returns new free_head index
dest_capacity specifies new array capacity
Returns
int
Definition at line 86 of file list.cpp.
                                                                                               {
    int res = LIST_ASSERT(list);
    assert(dest);
    assert(dest_free_head);
    assert(*dest == nullptr);
    assert((ssize_t)dest_capacity > list->size + 1);
    *dest = (ListNode*)calloc(dest_capacity, sizeof(ListNode));
    if (*dest == nullptr) {
        res |= list->ALLOC_ERR;
        LIST_OK(list, res);
        return res;
    }
    (*dest)[0] = {.prev = 0, .elem = ListNode::POISON, .next = 0};
    ssize_t old_i = list_head(list);
    ssize_t new_i = 0;
    while (old_i > 0) {
        (*dest)[new_i].next = new_i + 1;
        (*dest)[++new_i] = {.prev = new_i - 1, .elem = list->arr[old_i].elem, .next = 0};
        if (new_i > list->size) {
            res |= list->DAMAGED_PATH;
            LIST_OK(list, res);
            return res;
        }
        old_i = list->arr[old_i].next;
    }
    (*dest)[0].prev = new_i;
    *dest_free_head = new_i + 1;
    for (new_i = *dest_free_head; new_i < (ssize_t)dest_capacity; new_i++)
        (*dest)[new_i] = {.prev = list->UNITIALISED_VAL, .elem = ListNode::POISON, .next = new_i + 1};
    (*dest)[new_i - 1].next = 0;
    return res | LIST_ASSERT(list);;
}
References List::ALLOC_ERR, List::arr, List::DAMAGED_PATH, ListNode::elem, LIST_ASSERT, list_head(), LIST_OK, ListNode::next, ListNode::POISON, List::size, and List::UNITIALISED_VAL.
Referenced by list_resize().
list_logical_index_by_physical()
int list_logical_index_by_physical (const List * list, const ssize_t physical_i, ssize_t * logical_i)
Returns logical index of element with specified logical index.
Parameters
list
physical_i
logical_i returnable value. -1 if not finded
Returns
int
Definition at line 201 of file list.cpp.
                                                                                                   {
    assert(physical_i);
    int res = LIST_ASSERT(list);
    if (physical_i >= list->capacity || physical_i <= 0) {
        res |= list->INVALID_POSITION;
        LIST_OK(list, res);
        *logical_i = -1;
        return res;
    }
    ssize_t i = list_head(list);
    ssize_t log_i = 0;
    while (i > 0) {
        if (physical_i == i) {
            *logical_i = log_i;
            return res;
        }
        if (++log_i > list->size) {
            res |= list->DAMAGED_PATH;
            LIST_OK(list, res);
            *logical_i = -1;
            return res;
        }
        i = list->arr[i].next;
    }
    *logical_i = -1;
    return res;
}
References List::arr, List::capacity, List::DAMAGED_PATH, List::INVALID_POSITION, LIST_ASSERT, list_head(), LIST_OK, ListNode::next, and List::size.
list_print_error()
void list_print_error (const int err_code)
Prints text error to log by error code.
Parameters
err_code
Definition at line 362 of file list.cpp.
                                          {
    if (err_code == List::OK) {
        log_printf(&log_file, HTML_TEXT(HTML_GREEN("No error\n")));
    } else {
        PRINT_ERR_(ALREADY_INITIALISED, "Constructor called for already initialised or corrupted list");
        PRINT_ERR_(UNITIALISED, "List is not initialised");
        PRINT_ERR_(DATA_INVALID_PTR, "list.arr pointer is not valid for writing");
        PRINT_ERR_(ALLOC_ERR, "Can't allocate memory");
        PRINT_ERR_(POISON_VAL_FOUND, "There is poison value in list");
        PRINT_ERR_(NON_POISON_EMPTY, "Empty element is not poison");
        PRINT_ERR_(LOW_CAPACITY, "list.size > list.capacity - 1");
        PRINT_ERR_(NEGATIVE_CAPACITY, "Negative list.capacity");
        PRINT_ERR_(INVALID_CAPACITY, "Invalid capacity given");
        PRINT_ERR_(NEGATIVE_SIZE, "Negative list.size");
        PRINT_ERR_(INVALID_POSITION, "Invalid physical index given");
        PRINT_ERR_(DAMAGED_PATH, "List is damaged. Invalid path");
        PRINT_ERR_(INVALID_FREE_HEAD, "Invalid free_head field");
        PRINT_ERR_(INVALID_TAIL, "Invalid tail field");
        PRINT_ERR_(INVALID_HEAD, "Invalid head field");
        PRINT_ERR_(INVALID_IS_LINEAR, "is_linear flag is true, but list isn't linear");
    }
}
References HTML_GREEN, HTML_TEXT, log_file, log_printf(), List::OK, and PRINT_ERR_.
list_pushback()
int list_pushback (List * list, const Elem_t elem, size_t * inserted_index) [inline]
Inserts element at the end of the list.
Parameters
list
elem
inserted_index returns physical index of inserted element
Returns
int
Definition at line 150 of file list.h.
                                                                                {
    return list_insert_after(list, list_tail(list), elem, inserted_index);
}
References list_insert_after(), and list_tail().
list_pushfront()
int list_pushfront (List * list, const Elem_t elem, size_t * inserted_index) [inline]
Inserys element at the beginning of the list.
Parameters
list
elem
inserted_index returns physical index of inserted element
Returns
int
Definition at line 162 of file list.h.
                                                                                 {
    return list_insert_before(list, list_head(list), elem, inserted_index);
}
References list_head(), and list_insert_before().
list_resize()
int list_resize (List * list, size_t new_capacity)
Resizes list (realloc)
Parameters
list
new_capacity
Returns
int
Definition at line 59 of file list.cpp.
                                                 {
    int res = LIST_ASSERT(list);
    assert((ssize_t)new_capacity != list->capacity);
    ListNode* new_arr = nullptr;
    ssize_t new_free_head = -1;
    res |= list_linearise(list, &new_arr, &new_free_head, new_capacity);
    if (res != list->OK)
        return res;
    if (new_arr == nullptr) {
        res |= list->ALLOC_ERR;
        LIST_OK(list, res);
        return res;
    }
    FREE(list->arr);
    list->arr = new_arr;
    list->capacity = new_capacity;
    list->free_head = new_free_head;
    list->is_linear = true;
    return res | LIST_ASSERT(list);
}
References List::ALLOC_ERR, List::arr, List::capacity, FREE, List::free_head, List::is_linear, LIST_ASSERT, list_linearise(), LIST_OK, and List::OK.
Referenced by list_resize_down(), and list_resize_up().
list_resize_down()
int list_resize_down (List * list) [inline]
Checks if list capacity is too big and resizes it.
Parameters
list
Returns
int
Definition at line 401 of file list.h.
                                        {
    int res = LIST_ASSERT(list);
    ssize_t new_capacity = list->capacity;
    while (list->size < (new_capacity - 1) / 2)
        new_capacity = (new_capacity - 1) / 2 + 1;
    if (new_capacity != list->capacity)
        return res | list_resize(list, new_capacity);
    return res;
}
References List::capacity, LIST_ASSERT, list_resize(), and List::size.
Referenced by list_delete().
list_resize_up()
int list_resize_up (List * list) [inline]
Checks if list capacity is low and resizes it.
Parameters
list
Returns
int
Definition at line 381 of file list.h.
                                      {
    int res = LIST_ASSERT(list);
    ssize_t new_capacity = list->capacity;
    while (list->size >= new_capacity - 1 - 1)
        new_capacity = (new_capacity - 1) * 2 + 1;
    if (new_capacity != list->capacity)
        return res | list_resize(list, new_capacity);
    return res;
}
References List::capacity, LIST_ASSERT, list_resize(), and List::size.
Referenced by list_insert_after().
list_tail()
ssize_t list_tail (const List * list) [inline]
Returns list tail index.
Parameters
list
Returns
ssize_t
Definition at line 114 of file list.h.
                                           {
    return list->arr[0].prev;
}
References List::arr, and ListNode::prev.
Referenced by list_delete(), list_dump(), list_insert_after(), list_pushback(), and list_verify().
list_verify()
int list_verify (const List * list)
(Use macros LIST_VERIFY) Verifies list data and fields
Parameters
list
Returns
int
Definition at line 299 of file list.cpp.
                                  {
    assert(list);
    int res = list->OK;
    if (!list_is_initialised(list)) {
        res |= list->UNITIALISED;
        return res;
    }
    bool is_data_valid = true;
    if (!is_ptr_valid(list->arr)) {
        res |= list->DATA_INVALID_PTR;
        is_data_valid = false;
    }
    CHECK_ERR_(list->capacity < list->size + 1, list->LOW_CAPACITY);
    CHECK_ERR_(list->capacity < 0, list->NEGATIVE_CAPACITY);
    CHECK_ERR_(list->size < 0, list->NEGATIVE_SIZE);
    CHECK_ERR_(list->free_head <= 0, list->INVALID_FREE_HEAD);
    if (is_data_valid) {
        CHECK_ERR_(list_tail(list) < 0, list->INVALID_TAIL);
        CHECK_ERR_(list_head(list) < 0, list->INVALID_HEAD);
        ssize_t i = list_head(list);
        ssize_t bef_i = 0;
        ssize_t log_i = 0;
        while (i > 0) {
            CHECK_ERR_(list->arr[i].elem == ListNode::POISON, list->POISON_VAL_FOUND);
            CHECK_ERR_(list->arr[i].prev != bef_i, list->DAMAGED_PATH);
            CHECK_ERR_(list->is_linear && i != log_i + 1, list->INVALID_IS_LINEAR);
            if (++log_i > list->size) {
                res |= list->DAMAGED_PATH;
                break;
            }
            bef_i = i;
            i = list->arr[i].next;
        }
        CHECK_ERR_(log_i != list->size, list->DAMAGED_PATH);
        CHECK_ERR_(i < 0, list->DAMAGED_PATH);
        for (i = 1; i < list->capacity; i++) {
            CHECK_ERR_(list->arr[i].prev != -1 && list->arr[i].elem == ListNode::POISON,
                                                                           list->POISON_VAL_FOUND);
            CHECK_ERR_(list->arr[i].prev == -1 && list->arr[i].elem != ListNode::POISON,
                                                                           list->NON_POISON_EMPTY);
        }
    }
    return res;
}
References List::arr, List::capacity, CHECK_ERR_, List::DAMAGED_PATH, List::DATA_INVALID_PTR, ListNode::elem, List::free_head, List::INVALID_FREE_HEAD, List::INVALID_HEAD, List::INVALID_IS_LINEAR, List::INVALID_TAIL, List::is_linear, is_ptr_valid(), list_head(), list_is_initialised(), list_tail(), List::LOW_CAPACITY, List::NEGATIVE_CAPACITY, List::NEGATIVE_SIZE, ListNode::next, List::NON_POISON_EMPTY, List::OK, ListNode::POISON, List::POISON_VAL_FOUND, ListNode::prev, List::size, and List::UNITIALISED.
Variable Documentation
POISON_LIST_NODE
const ListNode POISON_LIST_NODE
Initial value:
= {ListNode::EMPTY_INDEX,
                                   ListNode::POISON,
                                   ListNode::EMPTY_INDEX}
Definition at line 33 of file list.h.
Referenced by list_dtor().