src/list_config.h File Reference
#include <ctype.h>
#include utils/macros.h
Classes
struct ListNode
struct List
Specifies List data.
Macros
#define DEBUG
#define ELEM_T_PRINTF %d
#define LIST_FOREACH(list_, phys_i_, log_i_) for (; phys_i_ > 0 && log_i_ <= (list_).size; phys_i_ = (list_).arr[phys_i_].next, (log_i_)++)
#define LIST_IS_FOREACH_VALID(list_, log_i_, ...)
Typedefs
typedef int Elem_t
Functions
bool list_is_initialised (const List *list)
Returns true if list was initialised.
ssize_t list_head (const List *list)
Returns list head index.
ssize_t list_tail (const List *list)
Returns list tail index.
Variables
const ListNode POISON_LIST_NODE
Macro Definition Documentation
DEBUG
#define DEBUG
Definition at line 8 of file list_config.h.
ELEM_T_PRINTF
#define ELEM_T_PRINTF %d
Definition at line 12 of file list_config.h.
LIST_FOREACH
#define LIST_FOREACH(list_, phys_i_, log_i_) for (; phys_i_ > 0 && log_i_ <= (list_).size; phys_i_ = (list_).arr[phys_i_].next, (log_i_)++)
Definition at line 108 of file list_config.h.
LIST_IS_FOREACH_VALID
#define LIST_IS_FOREACH_VALID(list_, log_i_, ...)
Value:
            do { \
            if (log_i_ != (list_).size) { \
                __VA_ARGS__; \
            } \
        } while (0)
Definition at line 111 of file list_config.h.
Typedef Documentation
Elem_t
typedef int Elem_t
Definition at line 10 of file list_config.h.
Function Documentation
list_head()
ssize_t list_head (const List * list) [inline]
Returns list head index.
Parameters
list
Returns
ssize_t
Definition at line 94 of file list_config.h.
                                           {
    return list->arr[0].next;
}
References List::arr, and ListNode::next.
Referenced by list_delete(), list_dump(), list_dump_dot(), list_find_by_logical_index(), list_find_by_value(), list_insert_after(), list_linearise(), list_logical_index_by_physical(), list_pushfront(), and list_verify().
list_is_initialised()
bool list_is_initialised (const List * list) [inline]
Returns true if list was initialised.
Parameters
list
Returns
true
false
Definition at line 81 of file list_config.h.
                                                  {
    return !(list->free_head == list->UNITIALISED_VAL &&
             list->capacity == list->UNITIALISED_VAL &&
             list->size == list->UNITIALISED_VAL &&
             list->is_linear == false && list->arr == nullptr);
}
References List::arr, List::capacity, List::free_head, List::is_linear, List::size, and List::UNITIALISED_VAL.
Referenced by list_ctor(), list_dump(), and list_verify().
list_tail()
ssize_t list_tail (const List * list) [inline]
Returns list tail index.
Parameters
list
Returns
ssize_t
Definition at line 104 of file list_config.h.
                                           {
    return list->arr[0].prev;
}
References List::arr, and ListNode::prev.
Referenced by list_delete(), list_dump(), list_dump_dot(), list_insert_after(), list_pushback(), and list_verify().
Variable Documentation
POISON_LIST_NODE
const ListNode POISON_LIST_NODE
Initial value:
= {ListNode::EMPTY_INDEX,
                                   ListNode::POISON,
                                   ListNode::EMPTY_INDEX}
Definition at line 26 of file list_config.h.
Referenced by list_dtor().